### ISSUE TITLE
req: ent save .ent, img save all (dump)

### ISSUE THREAD

**Issue by timbergeron** [jpiolho/QEBSPEditor#3]
ent save .ent, img save all as format of choice? (dump)

**Comment by jpiolho** [comment]
Entity file (.ent) export button added as part of ad06df56220ff8f7067f5082c400ae8d9f581fe2 in both Entity Source and Entity UI views

Will be adding the texture dump functionality after

**Comment by timbergeron** [comment]
Awesome ty!

**Comment by jpiolho** [comment]
Texture export button added. It supports exporting all textures as a WAD or a zip containing bmp, png, tga, tiff, gif, jpg or webp. 

00151b9248e7c2db63e2c7195d4bdbe942ff9bc6 09c85f4fe6c97d0ee49269db85acd64b2f90cfaa 2b16e2b6b65ed8f0beb103606f73a644cffd3d27

**Comment by timbergeron** [comment]
if there are special quake chars in the worldspawn they get corrupted on export

tested on ac4.bsp (http://files.crxquake.com/maps/)

<img width="651" alt="Screenshot 2023-11-11 at 8 04 41 AM" src="https://github.com/jpiolho/QEBSPEditor/assets/68674590/80004d61-f0e2-4d8b-a3a9-890e3b211c12"> vs 
<img width="412" alt="Screenshot 2023-11-11 at 8 09 31 AM" src="https://github.com/jpiolho/QEBSPEditor/assets/68674590/8926e664-f183-40d8-8194-81142d904916">

the file preview (so I can copy and paste) and export needs to be in windows 1252?

been working with this on:
https://www.timbergeron.com/name/
